### ISSUE TITLE
推送到halo的标题没有id作为锚点，导致右边文章目录点击不会自动定位

### ISSUE THREAD

**Issue by qqxpee** [halo-sigs/obsidian-halo#1]
插件版本为：1.0.1
问题描述：通过obsidian-halo发布到halo后，H2标题没有生成对应的id，导致右侧文章目录点击无法进行标题定位。使用halo网页版的发布之后会变好，但是一旦再次通过obsidian-halo发布会覆盖。

**Comment by qxq1994** [comment]
大佬，修这个的时候可以顺便添加一个可以指定别名的属性嘛？我看你代码好像是使用slugify(params.post.spec.title, { trim: true })来根据标题生成别名的，我就说我博客设置的是根据时间戳怎么无效，可以简单一点跟title一样设置什么就是什么

**Comment by ruibaby** [comment]
> 大佬，修这个的时候可以顺便添加一个可以指定别名的属性嘛？我看你代码好像是使用slugify(params.post.spec.title, { trim: true })来根据标题生成别名的，我就说我博客设置的是根据时间戳怎么无效，可以简

可以提供一个设置选项，这个建议新提交一个 issue。一个 issue 只处理一件事情。

**Comment by ruibaby** [comment]
/good-first-issue

修改方式可以参考：https://github.com/halo-sigs/vscode-extension-halo/pull/9

**Comment by ruibaby** [comment]
已经在 https://github.com/halo-sigs/obsidian-halo/commit/787f06c2d595f8ee517adae592bb8f7219e6ed31 中修复。

/close
