### ISSUE TITLE
请求增添元数据同步支持

### ISSUE THREAD

**Issue by 2019YKL** [halo-sigs/obsidian-halo#4]
❤ 非常感谢开发者开发这么一款好用的发布插件。

我注意到您目前**categories/tags**两个属性是支持同步的。

基于插件的功能建议，请问您是否考虑之后添加更多的元数据同步支持？

譬如：author,date,slug,summary,comments,cover(封面图),draft(用于判断发布与否)，link(返回文章链接，使得obsidian里可以直接点击)。

属性支持参考自Hugo文章属性和您相同类型的项目：[obsidian-to-NotionNext](https://github.com/jxpeng98/obsidian-to-NotionNext)

上述想法仅为个人提议，再次感谢您开发这款插件。

**Comment by ruibaby** [comment]
感谢支持，后续可以把文章中适合放在元数据的属性都放在元数据里。

**Comment by 2019YKL** [comment]
> 感谢支持，后续可以把文章中适合放在元数据的属性都放在元数据里。

😘 非常期待！祝Halo越来越好，祝您生活愉快~
