### ISSUE TITLE
发布的文章可否不进入草稿箱直接发布出来

### ISSUE THREAD

**Issue by colordi** [halo-sigs/obsidian-halo#6]
如题，插件使用起来非常方便，就是有一个问题，想要直接在Halo中发布可否实现？这样的话就不用单独进入一次Halo的后台进行管理了。

**Comment by ruibaby** [comment]
将 Front Matter 里的 halo.publish 手动改为 true，然后再发布即可。后续会提供一个设置选项，用于确定是否直接发布。

**Comment by colordi** [comment]
好的，谢谢
